name: Deploy to Dev

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  deploy-dev:
    # Reference the reusable workflow
    uses: TataHostIT/pipeline-templates/.github/workflows/build-deploy.yaml@main
    with:
      app_name: "fastapi-microservice-template"
      environment: "dev"
      values_file: "helm/dev-values.yaml"